Repository AustinfHunter/quatro-frontend, pull requests merged in 2024-11, with the labels that each got.

#9 integrate with backend fitness profile features
  src/components/Dashboard.js
  src/components/MacroChart.js
  src/components/Profile.js
  src/services/userService.js
Labels: 0.1.9

#10 fix bug on profile page
  src/components/Profile.js
Labels: 0.1.10

#11 ChatbotUI
  package-lock.json
  package.json
  src/components/Chatbot.js
  src/components/NavBar.js
  src/css/chatBotMessage.module.css
  src/index.js
  src/services/botService.js
Labels: 0.1.11, 0.1.11.1, 0.1.11.2

#13 Added Calorie Line Chart
  src/components/CalorieLineChart.js
  src/components/Dashboard.js
Labels: 0.1.13, 0.1.13.1

#15 sync chart to back-end
  src/components/CalorieLineChart.js
  src/components/Dashboard.js
  src/services/userService.js
Labels: 0.1.15

#16 integrate bot with new response format
  src/components/Chatbot.js
Labels: 0.1.16
